name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Multi-Platform Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Binaries
        run: |
          mkdir build
          GOOS=linux GOARCH=amd64 go build -o build/emailperm-linux-amd64 main.go
          GOOS=darwin GOARCH=amd64 go build -o build/emailperm-darwin-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o build/emailperm-darwin-arm64 main.go
          GOOS=windows GOARCH=amd64 go build -o build/emailperm-windows-amd64.exe main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}